PuebloPelicula/Models/Pelicula.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PuebloPelicula.Models
{
    public enum Tipo
    {
        Comercial,
        Documental
    }

    public abstract class Pelicula
    {

        public int ID { get; set; }

        [Required]
        [StringLength(60)]
        [Display(Name = "Titulo")]
        public string Titulo { get; set; }

        [Required]
        [Range(1, 360)]
        public Int32 Duracion { get; set; }

        //[Required]
        public string Foto { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }


        [StringLength(500)]
        public String Sinopsis { get; set; }
        
        public virtual IList<Funcion> Funciones { get; set; }

    }
}

PuebloPelicula/Controllers/PeliculasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PuebloPelicula.DAL;
using PuebloPelicula.Models;
using PuebloPelicula.ViewModels;

namespace PuebloPelicula.Controllers
{
    public class PeliculasController : Controller
    {
        private PuebloPeliContext db = new PuebloPeliContext();

        // GET: Peliculas
        public ActionResult Index(String Busqueda, int? CineElegido)
        {
          
            var query = from p in db.Peliculas select p;

            var peli_comercial = db.Peliculas.OfType<PeliComercial>().ToList();
            var peli_documental = db.Peliculas.OfType<PeliDocumental>().ToList();
            var pelicula = db.Peliculas.OrderBy(a => a.Titulo).ToList();
          
            var cines = db.Cines.ToList();
            ViewBag.CineElegido = new SelectList(cines, "CineID", "Nombre", CineElegido);
            int CineID = CineElegido.GetValueOrDefault();

            if (Busqueda != null)
            {
                pelicula = pelicula.Where(p => p.Titulo.ToLower().Contains(Busqueda.ToLower()) || p.Sinopsis.ToLower().Contains(Busqueda.ToLower())).ToList();

                peli_comercial = peli_comercial.Where(c => c.Actores.ToLower().Contains(Busqueda.ToLower())).ToList();
                pelicula.AddRange(peli_comercial.ToList());

                peli_documental = peli_documental.Where(d => d.Tema.ToString().ToLower() == Busqueda.ToLower()).ToList();
                pelicula.AddRange(peli_documental.ToList());

            }

            if (CineElegido != null)
            {



                IQueryable<Funcion> funciones = db.Funciones

                    .Where(c => /*!CineElegido.HasValue ||*/ c.Sala.CineID == CineID)
                    .OrderBy(d => d.Sala.CineID)
                    .Include(d => d.Sala.Cine);

                var peliCine = new List<Pelicula>();

                foreach (var f in funciones)
                {
                    peliCine.Add(f.Pelicula);
                }


                pelicula = peliCine.ToList();

            }


            PelisViewModel peliculas = new PelisViewModel()
            {
                Comercial = peli_comercial,
                Documental = peli_documental,
                Pelicula = pelicula,
       
            };

            return View(peliculas);



        }
        //public ActionResult Index()
        //{
        //    return View(db.Peliculas.ToList());
        //}

        // GET: Peliculas/Details/5
        public ActionResult Details(int? id)
        { 
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var comerciales = db.Peliculas.OfType<PeliComercial>();
            var documentales = db.Peliculas.OfType<PeliDocumental>();

            foreach (var pel in comerciales)
            {
                if (pel.ID == id)
                {
                    return RedirectToAction("Details", "PelisComerciales", new { id});
                }
            }
            foreach (var pel in documentales)
            {
                if (pel.ID == id)
                {
                    return RedirectToAction("Details", "PelisDocumentales", new { id });
                }
            }
            ViewBag.MensajeError = "La película no existe";
            return View("Error");
        }

 

        // GET: Peliculas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Peliculas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Titulo,Duracion,Foto,Sinopsis")] Pelicula pelicula)
        {
            if (ModelState.IsValid)
            {
                db.Peliculas.Add(pelicula);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pelicula);
        }

        // GET: Peliculas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pelicula pelicula = db.Peliculas.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        // POST: Peliculas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Titulo,Duracion,Foto,Sinopsis")] Pelicula pelicula)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pelicula).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pelicula);
        }

        // GET: Peliculas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pelicula pelicula = db.Peliculas.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        // POST: Peliculas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pelicula pelicula = db.Peliculas.Find(id);
            db.Peliculas.Remove(pelicula);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PuebloPelicula/Views/Peliculas/Create.cshtml
@model PuebloPelicula.Models.Pelicula

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pelicula</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duracion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duracion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duracion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Foto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sinopsis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sinopsis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sinopsis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PuebloPelicula/Views/Peliculas/Delete.cshtml
@model PuebloPelicula.Models.Pelicula

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pelicula</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duracion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duracion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Foto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sinopsis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sinopsis)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PuebloPelicula/Views/Peliculas/Details.cshtml
@model PuebloPelicula.ViewModels.PelisViewModel


@{
    ViewBag.Title = "Details";
}

<h2>Detalles de la Película:  @Html.DisplayFor(model => model.Pelicula) </h2>




<div>

    <dd>
        <img src="~/Imagenes/Peliculas/@Model.Foto" height="500" alt="imagen-peli" />
    </dd>

    <hr />
    <dl class="dl-horizontal">


        <dt>
            @Html.DisplayNameFor(model => model.Duracion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duracion)
        </dd>


        @if (Model is PuebloPelicula.Models.PeliComercial)
        {
            <h1>Es peli comercial</h1>
            <dt>
                @Html.DisplayNameFor(model => model.Actores)
            </dt>
        }

        @if (Model is PuebloPelicula.Models.PeliDocumental)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Tema)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EnExhibicion)
            </dd>
        }


        <dt>
            @Html.DisplayNameFor(model => model.EnExhibicion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnExhibicion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sinopsis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sinopsis)
        </dd>



    </dl>



</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Volver a la Lista", "Index")
</p>

PuebloPelicula/Views/Peliculas/Edit.cshtml
@model PuebloPelicula.Models.Pelicula

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pelicula</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duracion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duracion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duracion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Foto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sinopsis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sinopsis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sinopsis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PuebloPelicula/Views/Peliculas/Index.cshtml
@model PuebloPelicula.ViewModels.PelisViewModel
@using PuebloPelicula.Models


@{
    ViewBag.Title = "Pelis";

}

<h2>Pelis</h2>
@using (Html.BeginForm())
{
    <p class="form-group">
        <b>Buscar Peli: </b>@Html.TextBox("Busqueda", null, new { @class = "form-control" }) <br />
        <input type="submit" value="Búsqueda" class="btn btn-primary" />

        @Html.ActionLink("Mostrar todas las pelis", "Index", "Peliculas", null, new { @class = "btn btn-success" })
    </p>
}

@using (Html.BeginForm())
{
    <p>
        <b>Elegir Cine: </b>@Html.DropDownList("CineElegido", "Todos")
        <input type="submit" value="Buscar por cine" class="btn btn-warning" />
    </p>
}




@foreach (var peli in Model.Pelicula)
{
    @*if (peli.GetType().Name.Contains("PeliDocumental"))
        {
            <h3>Documental</h3>
        }
        if (peli.GetType().Name.Contains("PeliComercial"))
        {
            <h3>Comercial</h3>
        }*@


    <tr>

        <td>
            <h3>
                Peli:


                @Html.DisplayFor(modelItem => peli.Titulo)

                @if (peli.GetType().Name.Contains("PeliDocumental"))
                {
            <td>(Documental)</td>
        }
                @if (peli.GetType().Name.Contains("PeliComercial"))
                {
                    <td>(Comercial)</td>
                }

                </h3>
                </td>


            </tr>
            <tr>

                <td width="1">
                    <a href='@Url.Action("Details", new {id = peli.ID})'>
                        <img src="~/Imagenes/Peliculas/@peli.Foto" alt="foto-peli" height="10%" />
                    </a>
                </td>
            </tr>

        }