PuebloPelicula/Controllers/PelisDocumentalesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PuebloPelicula.DAL;
using PuebloPelicula.Models;

namespace PuebloPelicula.Controllers
{
    public class PelisDocumentalesController : Controller
    {
        private PuebloPeliContext db = new PuebloPeliContext();

        // GET: PelisDocumentales
        public ActionResult Index()
        {
            return View(db.Peliculas.ToList());
        }

        // GET: PelisDocumentales/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PeliDocumental peliDocumental = db.Documentales.Find(id);
            if (peliDocumental == null)
            {
                return HttpNotFound();
            }
            return View(peliDocumental);
        }

        // GET: PelisDocumentales/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PelisDocumentales/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create(PeliDocumental peliDocumental)
        {
            if (ModelState.IsValid)
            {
                peliDocumental.Foto = peliDocumental.ImageFile.FileName;
                peliDocumental.ImageFile.SaveAs(Server.MapPath("~/Imagenes/Peliculas") + "/" + peliDocumental.ImageFile.FileName);

                db.Peliculas.Add(peliDocumental);
                db.SaveChanges();
                return RedirectToAction("Index", "Peliculas");
            }

            return View(peliDocumental);
        }

        // GET: PelisDocumentales/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PeliDocumental peliDocumental = db.Documentales.Find(id);
            if (peliDocumental == null)
            {
                return HttpNotFound();
            }
            return View(peliDocumental);
        }

        // POST: PelisDocumentales/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Titulo,Duracion,Foto,Sinopsis,Tema")] PeliDocumental peliDocumental)
        {
            if (ModelState.IsValid)
            {
                db.Entry(peliDocumental).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(peliDocumental);
        }

        // GET: PelisDocumentales/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PeliDocumental peliDocumental = db.Documentales.Find(id);
            if (peliDocumental == null)
            {
                return HttpNotFound();
            }
            return View(peliDocumental);
        }

        // POST: PelisDocumentales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PeliDocumental peliDocumental = db.Documentales.Find(id);
            if (peliDocumental.Funciones.Count() == 0)
            {
                db.Peliculas.Remove(peliDocumental);
                db.SaveChanges();
                return RedirectToAction("Peliculas", "Index");
            }
            ViewBag.Mensaje = "No se puede borrar la película porque está en exhibición";
            return View("Error");

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PuebloPelicula/Views/PelisDocumentales/Create.cshtml
@model PuebloPelicula.Models.PeliDocumental

@{
    ViewBag.Title = "Agregar Peli Documental";
}

<h2>Agregar Peli Documental</h2>


@using (Html.BeginForm("Create", "PelisDocumentales", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Duracion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Duracion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Duracion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Subir imagen</label>
        @Html.TextBoxFor(model => model.ImageFile, new { Type = "File", required = "required" })
        @Html.ValidationMessageFor(model => model.ImageFile)

    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sinopsis, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Sinopsis, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Sinopsis, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Tema, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Tema, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Tema, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Volver", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PuebloPelicula/Views/PelisDocumentales/Delete.cshtml
@model PuebloPelicula.Models.PeliDocumental

@{
    ViewBag.Title = "Borrar película";
}

<h2>Borrar película</h2>

<h3>Seguro querés borrar la peli @Html.DisplayFor(model => model.Titulo) ?</h3>


    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Borrar" class="btn btn-default" /> |
    @Html.ActionLink("Volver", "Index", "Peliculas")
    </div>
    }
</div>

PuebloPelicula/Views/PelisDocumentales/Details.cshtml
@model PuebloPelicula.Models.PeliDocumental

@{
    ViewBag.Title = "Detalle";
}

<h2>Detalle</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">

        <div style="float:center">
            <img src="~/Imagenes/Peliculas/@Model.Foto" height="700" alt="poster" />
        </div>

        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duracion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duracion) minutos
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Sinopsis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sinopsis)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Tema)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tema)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Funciones)
        </dt>
        <dd>
            @foreach (var item in Model.Funciones)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.Sala.NombreSala)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Horario)
                    </td>

                </tr><br />
            }
        </dd>
        @if (Request.IsAuthenticated)
        {
            <td>
                @Html.ActionLink("Borrar la película", "Delete", new { id = Model.ID })
            </td>

        }

    </dl>
</div>
<p>
    @Html.ActionLink("Volver", "Index", "Peliculas")
</p>

PuebloPelicula/Views/PelisDocumentales/Edit.cshtml
@model PuebloPelicula.Models.PeliDocumental

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PeliDocumental</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duracion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duracion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duracion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Foto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sinopsis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sinopsis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sinopsis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tema, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Tema, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Tema, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PuebloPelicula/Views/PelisDocumentales/Index.cshtml
@model IEnumerable<PuebloPelicula.Models.PeliDocumental>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Duracion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Foto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sinopsis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tema)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Duracion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Foto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sinopsis)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tema)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>